// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnbkzvcuxmzonvcjsilj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduYmt6dmN1eG16b252Y2pzaWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODc2MTAsImV4cCI6MjA2Mjg2MzYxMH0.uwz96jCdAZ190iqo5xlQpNhYOOAd7kfmKrA3KjRHF_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);